### ISSUE TITLE
Expose isActive state

### ISSUE THREAD

**Issue by SimonMarquis** [YarikSOffice/venom#19]
Venom uses its own `SharedPreferences` file to store its `active` state: `VenomPreferenceManager.kt`.
Unfortunately this state is private and leads to some issues.
For instance, suppose my app is bundled with a dedicated _debug panel_ where you can toggle features.
There is currently no way (other than hardcoding the same SharedPreferences file name and key) to sync with Venom internal state.
Disabling Venom with the `cancel` notification action will not change the host setting, and vice-versa. Which means that, when the app is later re-started, my host will try to start Venom again.
It would be great to allow the host to get, or even set this internal state. Maybe `setActive`/`isActive` isn't the right wording for that.

**Comment by YarikSOffice** [comment]
In the current implementation `venom.isRunning()` is equivalent to `isActive()` since they are always changed at the same time. Therefore, `isRunning()` can be safely used in your _debug panel_ to indicate the current state. You can also use start/stop to toggle the service on and off. The only missing part here is a listener that will notify the debug panel of the state change. We can consider adding it in the upcoming releases.

@SimonMarquis do you think it will cover your use case?

**Comment by SimonMarquis** [comment]
> In the current implementation venom.isRunning() is equivalent to isActive() since they are always changed at the same time.
True, even though `isRunning` value is async if we compare it to `isActive`. The Service must be inflated first, then started, and then it is reported as running.

So from what I understand `initialize()` should always be called, even if we don't want it (when feature is turned off).

Then I can't see a good way to start Venom by default on first app launch without having another preference to keep track of this first launch.

**Comment by YarikSOffice** [comment]
>So from what I understand initialize() should always be called, even if we don't want it (when feature is turned off).

Technically, it's not obligatory to call `initialize()` on every app launch, but you have to call it before any usage of Venom. What this method does is restore the state of the service according to `isRunning` setting.

>Then I can't see a good way to start Venom by default on first app launch without having another preference to keep track of this first launch.

Yes, you have to use a custom preference to automatically start Venom on the very first app launch only. You have to do it manually since this is not the way how it's designed to work.

**Comment by SimonMarquis** [comment]
Thanks for the clarification.
